// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBwOfXFz0UQXtjxIhHciJGJwn2XmlvPg',
    appId: '1:398132663697:web:b824f39c90fe337d13f630',
    messagingSenderId: '398132663697',
    projectId: 'flutter-520a5',
    authDomain: 'flutter-520a5.firebaseapp.com',
    databaseURL: 'https://flutter-520a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-520a5.appspot.com',
    measurementId: 'G-T5Y8TH6756',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqROvuxSLyguGUidokeM4xyNigNdO3eM',
    appId: '1:398132663697:android:417e3436333cf4e413f630',
    messagingSenderId: '398132663697',
    projectId: 'flutter-520a5',
    databaseURL: 'https://flutter-520a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-520a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIauISGw_ewGlRlcaFFtnhe_syEitb0I',
    appId: '1:398132663697:ios:9507dd963fa23a3113f630',
    messagingSenderId: '398132663697',
    projectId: 'flutter-520a5',
    databaseURL: 'https://flutter-520a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-520a5.appspot.com',
    iosClientId: '398132663697-83eik0rnhqk5accfanqv5vio39gdgknp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIauISGw_ewGlRlcaFFtnhe_syEitb0I',
    appId: '1:398132663697:ios:9507dd963fa23a3113f630',
    messagingSenderId: '398132663697',
    projectId: 'flutter-520a5',
    databaseURL: 'https://flutter-520a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-520a5.appspot.com',
    iosClientId: '398132663697-83eik0rnhqk5accfanqv5vio39gdgknp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvp',
  );
}
